<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[ Home page is not Displayed]]>
    </line>
    <line>
      <![CDATA[TesttestValidLogin is failed]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="36448" started-at="2019-10-09T06:22:14Z" finished-at="2019-10-09T06:22:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36448" started-at="2019-10-09T06:22:14Z" finished-at="2019-10-09T06:22:51Z">
      <class name="Test_Pom.TestValidLogin">
        <test-method status="PASS" signature="openapp()[pri:0, instance:Test_Pom.TestValidLogin@33a10788]" name="openapp" is-config="true" duration-ms="22741" started-at="2019-10-09T11:52:14Z" finished-at="2019-10-09T11:52:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method status="FAIL" signature="testValidLogin()[pri:0, instance:Test_Pom.TestValidLogin@33a10788]" name="testValidLogin" duration-ms="8635" started-at="2019-10-09T11:52:37Z" finished-at="2019-10-09T11:52:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at Pom.EnterTimeTrackPage.verifyHPisDisplayed(EnterTimeTrackPage.java:24)
	at Test_Pom.TestValidLogin.testValidLogin(TestValidLogin.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[ Home page is not Displayed]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:Test_Pom.TestValidLogin@33a10788]" name="closeApp" is-config="true" duration-ms="5051" started-at="2019-10-09T11:52:46Z" finished-at="2019-10-09T11:52:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidLogin status=FAILURE method=TestValidLogin.testValidLogin()[pri:0, instance:Test_Pom.TestValidLogin@33a10788] output= Home page is not Displayed]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[TesttestValidLogin is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- Test_Pom.TestValidLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
